services:
  - type: web
    name: csitmitra
    env: python
    buildCommand: pip install -r requirements.txt && python nltk_setup.py
    startCommand: gunicorn app:app --workers 2 --timeout 60
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
